version: '3.2'
services:
  bash:
    image: ruby:2.3
    working_dir: /opt/ruby
    volumes:
      - type: bind
        source: .
        target: /opt/ruby
    entrypoint: bash 
  irb:
    image: ruby:2.3
    working_dir: /opt/ruby
    volumes:
      - type: bind
        source: ./irb
        target: /opt/ruby
    entrypoint: irb
