version: '3.2'
services:
  ruby:
    image: ruby:2.3
    volumes:
      - type: bind
        source: .
        target: /opt/ruby
    working_dir: /opt/ruby
  bash:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /opt/ruby
    working_dir: /opt/ruby
    entrypoint: bash
